### ISSUE TITLE
Use xPath to select elements to run against to pierce the Shadow DOM

### ISSUE THREAD

**Issue by tylerl-ms** [microsoft/axe-pipelines-samples#1096]
We integrated AxeCore into our test harness. Developers can easily specify a selector to run tests against their feature, however AxeCore appears to use document.querySelectorAll which cannot search in our features because we use Web Components and the Shadow DOM - even though we have the "open" property set. This means tests run against a whole page and not a specific feature.

Is there a way AxeCore can be updated to use xPath or another way to select from the DOM that works with Web Components?

**Comment by lisli1** [comment]
The [axe API documentation](https://www.deque.com/axe/core-documentation/api-documentation/#context-parameter) gives examples of using `include`/`exclude` to test specific elements in the page. Is this something that would work for you?
