### ISSUE TITLE
Exclude Test Failures from Previous Test Run to Reset Baseline

### ISSUE THREAD

**Issue by easy0924** [microsoft/axe-pipelines-samples#157]
## Is your feature request related to a problem? Please describe.
It would be nice if we could reset the test result baseline and exclude test failures from previous test runs. We used to have this feature with the old Chisel package, through DevOps configurations.

## Describe the desired outcome
This feature maybe complicated, as it needs to allow test failure exclusions during run time, instead of exclude tests in code through CSS selectors and specific rules, which are already possible.

## Describe alternatives you've considered
There isn't an exact alternative approach at this moment based on developers' feedback. We could exclude tests in code with selectors and rules, but that requires code changes every time a new issue comes up.

## Additional context
To reset baseline this way was possible with old Chisel package and DevOps configurations

**Comment by adarshrema** [comment]
@easy0924, thank you for using one of our samples and for this feedback. We explored using [sarif sdk](https://github.com/microsoft/sarif-sdk) for this but think that the complexity does not justify the resulting benefit. We will keep this on our backlog to assess interest among the community and keep exploring other solution options.

**Comment by asksep** [comment]
The Accessibility Insights team has guidance on how to do more custom baselining through our [ADO Extension](https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md#using-a-baseline-file)'s Baseline Capability.
