### ISSUE TITLE
Include sample for creating bug filing link just as with the Accessibility Insights browser extension's FastPass tool

### ISSUE THREAD

**Issue by thisisnaty** [microsoft/axe-pipelines-samples#1576]
We use the Accessibility Insights FastPass tool on the browser to create bugs. To automate this process, we're integrating Accessibility Insights FastPass with Playwright tests. It would be very helpful to be able to generate a link for filing bugs, same as the functionality provided by the Accessibility Insights browser extension. This would streamline our workflow and improve efficiency.

**Comment by joestegman425** [comment]
Thank you for the feedback; however, we are not planning to do this request. See [#1359](https://github.com/microsoft/axe-sarif-converter/issues/1359) for details.
