### ISSUE TITLE
Include ability to run tests as admin

### ISSUE THREAD

**Issue by cathymc** [microsoft/axe-pipelines-samples#163]
**Issue:**
When initally running the tests on my machine, I used the Developer Command Prompt for VS2017 as an admin. Once I ran 'yarn test', I received the following error message:
```
RUNS  tests/index.test.ts
(node:11356) UnhandledPromiseRejectionWarning: WebDriverError: unknown error: unable to discover open pages
(node:11356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The error message wasn't helpful enough for me to find the issue and I was stuck trying to prevent my Chrome driver from crashing.

Eventually, I reopened the Command Prompt as a non-admin, ran 'yarn test' and had no issues.

**Desired Behavior:**
It would be better to have a more detailed error description for running the tests as an admin. Additionally, the ability to run the tests as admin would be ideal since our team usually runs our other Jest tests in that way already.

**Comment by adarshrema** [comment]
Add ability to run tests as admin or at the minimum improve the error message to be actionable. Per @dbjorge, we encountered this issue in accessibility-insights-web repo and fixed it. Recommended to follow the same approach and document it in the sample.

**Comment by dbjorge** [comment]
This appears to have been resolved on chrome/chromedriver's side since the bug was filed; I'm now able to run the tests successfully from an admin command prompt.
