### ISSUE TITLE
Add UWP support and sample

### ISSUE THREAD

**Issue by benabbon** [microsoft/axe-pipelines-samples#174]
## Describe the desired outcome
I'd love to be able to add accessibility testing to my pipeline. I have a UWP app and UWP unit test project that contains UI Test. I'm able to run them in azure-pipelines using the WinAppDriver.

## Describe alternatives you've considered
I tried following the sample for csharp against a web page. Using Selenium.Axe conflicts with the Microsoft.WinAppDriver.Appium.WebDriver that allows me to run UI tests (they depend on different versions of the Selenium.WebDriver, and the latest doesn't work for UWP).

**Comment by adarshrema** [comment]
Hello @benabbon, thank you for this feature request. We recommend using [Axe.Windows](https://github.com/microsoft/axe-windows) as demonstrated in [this project](https://github.com/microsoft/accessibility-insights-windows/tree/master/src/UITests) to implement automated accessibility tests for a Windows application. Selenium.axe is intended for Web projects.

From issue [#251](https://github.com/microsoft/axe-windows/issues/251), it looks like your team is on the right path. We will keep this issue open to find out commmunity interest in a sample demonstrating automated accessibility tests for Windows applications.

**Comment by asksep** [comment]
Moved to close as thread has not received any new traction/updates/comments since filing 3 years ago and was addressed with recommendation to use Axe.Windows.
