### ISSUE TITLE
testcafe sample to be added

### ISSUE THREAD

**Issue by hasans30** [microsoft/axe-pipelines-samples#184]
## Is your feature request related to a problem? Please describe.
feature request - we are using testcafe for web automation. not found example of axe-pipelines on how to use for testcafer
https://github.com/DevExpress/testcafe

## Describe the desired outcome
testcafe axe a11y automation sample to be provided

**Comment by adarshrema** [comment]
Hello @hasans30, thank you for your interest in Accessibility Insights and this feature request. You should be able to use the [axe-core integration to testcafe](https://github.com/helen-dikareva/axe-testcafe) and follow documentation available in one of the samples to integrate automated accessibility checks in engineering pipeline. Even when the samples are specific to Selenium integration to axe-core, the concepts are applicable and extendable to any UI test frameworks like testcafe, Protractor, Cypress, etc.

Please let us know if you run into issues. We will keep this request open to assess the community interest in a separate sample for testcafe.

**Comment by asksep** [comment]
Moved to close as was resolved with recommendation by Dec. 2019 comment.
