### ISSUE TITLE
Feedback from user study: The root level readme page confusing for participants. 

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#26]
When participants initially landed on this page, they were distracted by links. None of the three participants successfully found the link to the sample on this page. One participant was confused by the name and thought it was a web driver, not a sample. Also, the immediate link to Axe was confusing. Two users immediately clicked on the link and were confused as to why they were being brought to this page. One user was confused and was not sure what the repo has to do with Accessibility Insights. One user realized after some time that the sample (typescript) was not relevant to his team (C#).

Recommendations: 
•	Update summary to introduce the solution better and establish connection with axe.
•	Update axe link to point to axe-core repo. Clearly differentiate link to axe from link to the sample.
•	Update summary to spell out which sample is relevant for what team.
•	Change the name of the sample to something more obvious, and make the link to sample more prominent
•	Consider having different pages for different samples

**Comment by ferBonnin** [comment]
since this is closed marking it as resolved
