### ISSUE TITLE
Feedback from user study: Users need more context about the content of the overview page

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#28]
Participants were not sure about what the repo is trying to accomplish. One participant requested a high-level summary at the start of the page to give more context about what the user should expect to do and what the output will be. One user thought a short video describing the project would be a good idea for an overview.
Recommendation:
•	Provide users with a high-level summary of the process and a table of contents to organize information
•	Provide a clearer picture of what the end state looks like and step by step instructions to get there.

**Comment by lisli1** [comment]
Closing this issue because it is closely related to #29
