### ISSUE TITLE
typescript-selenium-webdriver-sample: Firefox job flakiness

### ISSUE THREAD

**Issue by dbjorge** [microsoft/axe-pipelines-samples#318]
## Describe the bug

Recently, we've been seeing about 30% of CI/PR builds show a failure during setup of the geckodriver<->Firefox connection in the firefox test job. We haven't root caused the issue or why it became markedly worse in the last 1-2 months; this bug tracks that work.

**Comment by asksep** [comment]
Moved to closed as this looks to have been resolved by recent Selenium updates
