### ISSUE TITLE
Feedback from user study: The sample project is complex

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#33]
Participants reviewing files that make up the sample project felt that,
•	It would have been nice to start with a simpler scenario than including possible variations that are confusing and overwhelming
•	Not sure how to get started
•	Too heavy with data/ information
•	Most of this can be done outside Azure pipelines
•	Not confident that this is reliable and maintainable

Recommendation:
Simplify the sample project to the most basic scenario with options to build over it incrementally

**Comment by adarshrema** [comment]
PM to review feedback from user studies, review issues that have been fixed since the user study, reach out to onboarding teams for feedback - before updating this issue with specific resolution comments.

**Comment by asksep** [comment]
Moved to close as thread has not received any traction/updates/comments since filing 3 years ago. The Accessibility Insights team regularly checks-in with teams for feedback and improvement-requests.
