### ISSUE TITLE
Add axe-windows samples for Win32 (non-UWP)

### ISSUE THREAD

**Issue by roryfa** [microsoft/axe-pipelines-samples#421]
**Describe the desired outcome**
I'd love to be able to add accessibility testing to our application's engineering pipeline. Our application is native Win32 and the samples we've seen here are focus on apps that are implemented using web technologies.

**Comment by adarshrema** [comment]
@roryfa, thank you for your interest in the samples and for this feature request. We have added [WindowsAppResources](https://github.com/microsoft/axe-pipelines-samples/tree/master/windows-app-resources) under Other Resources section in the readme to help with this. Hope this helps.
