### ISSUE TITLE
Disclaimer section of sample README discourages use of the sample

### ISSUE THREAD

**Issue by dbjorge** [microsoft/axe-pipelines-samples#43]
One of our users in a user study told us after reading our Disclaimer text that they weren't sure they'd have continued implementing automated tests at all after having read it; they felt like they weren't convinced it would be valuable.

We discussed rewording the disclaimer to be more encouraging in #41 and offline with @ferBonnin; we want to maintain the spirit of the disclaimer and the pointer to Accessibility Insights, but we think there's room to try to have the disclaimer text be a bit more positive about automated testing still being valuable and worth doing as a first step, even if it won't catch all/most issues.

**Comment by adarshrema** [comment]
Review disclaimer text to include benefits of integrating automated checks in engineering pipeline.

**Comment by adarshrema** [comment]
Update Disclaimer section text to:
Automated accessibility tests can detect some common accessibility problems such as missing or invalid properties. But most accessibility problems can only be discovered through manual testing. We recommend *both* automated testing, to continuously protect against simple types of issues, *and* regular manual assessments with [Accessibility Insights](https://accessibilityinsights.io/docs/en/web/overview), a free and open source dev tool that walks you through assessing a website for 100% WCAG 2.1 AA coverage.

•	“Automated accessib
