### ISSUE TITLE
axe-android automated testing

### ISSUE THREAD

**Issue by ferBonnin** [microsoft/axe-pipelines-samples#460]
## Is your feature request related to a problem? Please describe.

This is a feature request for a sample on how to integrate the axe-android checks in the CI/CD pipeline

## Additional context

This has been a request from user feedback and pilot teams. Adding it here as a reference to group upvotes and comments. We also need to understand what type of E2E framework most teams use in their build pipelines. We have heard Espresso.
We would be happy to take a contribution on a team that has integrated these tests in their pipeline.

**Comment by adarshrema** [comment]
Keeping this open to assess community interest and while we do some internal investigation.
