### ISSUE TITLE
Sample request: axe-puppeteer

### ISSUE THREAD

**Issue by dbjorge** [microsoft/axe-pipelines-samples#50]
We got a report from an internal customer we sent the sample to that, based on the existing selenium-based sample, they had added a Selenium dependency to get a11y testing in place even though they already had Puppeteer-based end to end tests in place.

It would be nice to have a sample using [axe-puppeteer](https://github.com/dequelabs/axe-puppeteer) to prevent other teams doing the same

**Comment by Shobhit1** [comment]
I have been using `axe-puppeteer` on the docs side of the things. Might be a good reference point for adding a test using that library.
https://github.com/microsoft/accessibility-insights-docs/blob/master/website/end-to-end/common/scan-for-accessibility-issues.js#L3

**Comment by adarshrema** [comment]
Added help wanted label to guage community interest and needs investigation to assess interest of such a sample within internal teams.

**Comment by DaveTryon** [comment]
Sadly, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
