### ISSUE TITLE
Selenium sample should clarify applicability to teams using other browser automation test frameworks 

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#51]
We got a report from an internal customer we sent the sample to that, based on the existing selenium-based sample, they had added a Selenium dependency to get a11y testing in place even though they already had Puppeteer-based end to end tests in place.

Suggested resolution:
Update the Selenium sample readme to clarify that Even if a team is not using Selenium and are using a different browser automation framework, many of them already have specific open source libraries for integrating axe scans (puppeteer has axe-puppeteer, webdriverio has axe-webdriverio, cypress has cypress-axe). Most of the concepts from the Selenium sample would be the same, but they would want to use the axe integration library most relevant to the framework they are using.

**Comment by ferBonnin** [comment]
since this is closed marking it as resolved
