### ISSUE TITLE
Link in the Selenium sample poins to the wrong page

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#52]
In the Selenium sample, the [link](https://dev.azure.com/accessibility-insights/axe-pipelines-samples/_build/results?buildId=1283&view=sariftools.sarif-viewer-build-tab.sariftools.sarif-viewer-build-tab) embedded in ‘Screenshot of Scans tab in sample build’ graphic under section ‘See it in action in Azure Pipelines’ currently does not display scan results as intended.

Resolution:
1.	Update the link embedded in the graphic to point to the correct page that displays failure details from the latest scan, as is [here](https://dev.azure.com/accessibility-insights/axe-pipelines-samples/_build/results?buildId=2228&view=sariftools.sarif-viewer-build-tab.sariftools.sarif-viewer-build-tab).
2.	Update the screen shot (the link is embedded in), if necessary

Attachments:
Current screen.png: Screen shot of page that the link is pointing to currently
Scans results.png: Screen shot of the Scans tab with failure details (how this page should ideally look like)
<img width="1920" alt="current screen" src="https://user-images.githubusercontent.com/48295243/62737070-d2fcac00-b9e3-11e9-8fb4-5b27a152c421.png">
<img width="1920" alt="Scans results" src="https://user-images.githubusercontent.com/48295243/62737114-ead43000-b9e3-11e9-8102-b23fe251ccae.png">

**Comment by dbjorge** [comment]
Fixed by #54
